### ISSUE TITLE
TODO list for new web site

### ISSUE THREAD

**Issue by andreasprlic** [biojava/biojava.github.io#4]
- [ ] host old Maven repository
- [x] host API javadocs
- [ ] fix Category pages (using tags)

**Comment by andreasprlic** [comment]
The new Maven repo is available at

https://github.com/biojava/maven-repo/tree/master

You can add it to your project's pom.xml by adding

```xml
<repository>
    <id>biojava-legacy-repo</id>
    <name>BioJava's Git based legacy maven repo</name>
    <url>https://github.com/biojava/maven-repo/raw/master/</url>
</repository>
```
